export const paths = {
  getRoot: () => "/",
  getCourses: () => "/courses",
  getStudents: () => "/student",
  getRegisterStudentsEdit: (id) => `/student/edit/${id}`,
  getRegisterStudents: () => "/student/register",
  getCourseAdd: () => "/courses/add",
  getCourseEdit: (id) => `/courses/edit/${id}`,
  getDashboard: () => "/dashboard",
  getPayFee: () => "/pay_fee",
  getTransactions: () => "/transactions",
  getLogin: () => "/login",
  getRegisterUsers: () => "/user/register",
  getUsersEdit: (id) => `/user/edit/${id}`,
  getUsersList: () => "/users",
};
